FROM nginx:latest

RUN apt-get update && apt-get install -y openssl

COPY nginx.conf /etc/nginx/nginx.conf
COPY conf.d /etc/nginx/conf.d

RUN mkdir -p /etc/ssl/certs /etc/ssl/private && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/private/nginx-selfsigned.key \
    -out /etc/ssl/certs/nginx-selfsigned.crt \
    -subj "/C=BR/ST=São Paulo/L=São Paulo/O=Minha Empresa/OU=TI/CN=fundamentos.exemplo.com.br"

RUN rm /etc/nginx/conf.d/default.conf
